-- ==========================================
-- MANASVI FASHION — SUPABASE DATABASE SCHEMA
-- ==========================================

-- ============================================================
-- 0. Products Table (Public catalogue — no auth required to read)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY DEFAULT 'p-' || extract(epoch from now())::text,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,                           -- 'kurtis' | 'dresses'
    product_type TEXT NOT NULL,                       -- 'kurti' | 'tunic_top' | 'dress'
    subcategory TEXT,
    description TEXT NOT NULL DEFAULT '',
    fabric TEXT,
    sleeve_type TEXT,
    color TEXT,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    compare_at_price NUMERIC(10, 2),
    sizes JSONB NOT NULL DEFAULT '[]',                -- string[] e.g. ["S","M","L"]
    images JSONB NOT NULL DEFAULT '[]',               -- string[] of image paths
    stock INTEGER NOT NULL DEFAULT 0,
    rating NUMERIC(3, 1) DEFAULT 5.0,
    reviews INTEGER DEFAULT 0,
    is_new BOOLEAN DEFAULT false,
    color_variants JSONB DEFAULT '[]',                -- [{name, hex, image}]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow ANYONE (anon + authenticated) to read products — public catalogue
CREATE POLICY "Public can read products" ON public.products
    FOR SELECT TO anon, authenticated
    USING (true);

-- Only authenticated admins can insert/update/delete products
CREATE POLICY "Admins can manage products" ON public.products
    FOR ALL TO authenticated
    USING (true)
    WITH CHECK (true);

-- 1. Users Table (Secure authentication & authorization profiles)
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'seller', 'customer')) DEFAULT 'customer',
    phone TEXT,                              -- Optional phone number for checkout notifications
    shipping_address TEXT,                   -- Pre-saved physical address for express delivery
    city TEXT,                               -- Saved city
    postal_code TEXT,                        -- Saved postal pincode
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Users Table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Security Policies for Users Table
CREATE POLICY "Allow users to read their own profile" ON public.users
    FOR SELECT TO authenticated
    USING (auth.uid()::text = id OR email = auth.jwt()->>'email');

CREATE POLICY "Allow public registration inserts" ON public.users
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);


-- 2. Orders Table (Wardrobe acquisitions & purchase records)
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    items JSONB NOT NULL, -- Detailed order line items [ { productId, title, price, qty, size, image, slug } ]
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'returned', 'cancelled')) DEFAULT 'pending',
    payment_status TEXT NOT NULL CHECK (payment_status IN ('paid', 'unpaid', 'failed', 'refunded')) DEFAULT 'unpaid',
    shipping_address TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Orders Table
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Security Policies for Orders Table
CREATE POLICY "Allow users to view their own orders" ON public.orders
    FOR SELECT TO authenticated
    USING (customer_email = auth.jwt()->>'email');

CREATE POLICY "Allow secure checkout inserts" ON public.orders
    FOR INSERT TO authenticated
    WITH CHECK (customer_email = auth.jwt()->>'email');


-- 3. Contact Submissions Table (Public inquiry captures)
CREATE TABLE IF NOT EXISTS public.contact_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    inquiry_type TEXT NOT NULL CHECK (inquiry_type IN ('styling', 'order', 'collaboration', 'general')),
    message TEXT NOT NULL
);

-- Enable RLS for Contact Submissions
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous inserts" ON public.contact_submissions
    FOR INSERT TO anon
    WITH CHECK (true);

CREATE POLICY "Allow authenticated reads" ON public.contact_submissions
    FOR SELECT TO authenticated
    USING (true);


-- ==============================================================
-- HANDY SUPABASE QUERIES FOR LOGIN, REGISTER & PURCHASE HISTORY
-- ==============================================================

-- A. Registering a New User with Detailed Profile Information (Real user capture)
-- Note: Replace placeholders with secure values. password_hash must be pre-hashed in BCrypt.
-- INSERT INTO public.users (id, name, email, password_hash, role, phone, shipping_address, city, postal_code)
-- VALUES (
--     'usr-1716298102', 
--     'Aishwarya Rai', 
--     'aishwarya@example.com', 
--     '$2a$10$hashedSecureBcryptString', 
--     'customer',
--     '+919988776655', 
--     'Bungalow 4, Juhu Scheme', 
--     'Mumbai', 
--     '400049'
-- );


-- B. Authenticating / Logging in a User (Fetch user details by email)
-- SELECT id, name, email, password_hash, role, phone, shipping_address, city, postal_code 
-- FROM public.users 
-- WHERE email = 'aishwarya@example.com';


-- C. Inserting a New Purchase Order (Placed during secure checkout payment success)
-- INSERT INTO public.orders (id, customer_name, customer_email, customer_phone, items, total_amount, status, payment_status, shipping_address)
-- VALUES (
--     'ORD-928103',
--     'Aishwarya Rai',
--     'aishwarya@example.com',
--     '+919988776655',
--     '[{"productId": "p1", "title": "Elara Signature Kurti", "price": 3499, "qty": 1, "size": "M", "image": "/photos/elara.png", "slug": "elara-signature-kurti"}]'::jsonb,
--     3499.00,
--     'processing',
--     'paid',
--     'Bungalow 4, Juhu Scheme, Mumbai, MH - 400049'
-- );


-- D. Fetching All Purchased Products for a Given User (Orders History query)
-- This extracts the nested items JSONB array to report exactly which individual products the customer has bought!
-- SELECT 
--     o.id AS order_id,
--     o.created_at,
--     o.status AS order_status,
--     o.payment_status,
--     item->>'productId' AS product_id,
--     item->>'title' AS product_title,
--     (item->>'price')::numeric AS unit_price,
--     (item->>'qty')::int AS quantity,
--     item->>'size' AS selected_size
-- FROM public.orders o,
-- LATERAL jsonb_array_elements(o.items) AS item
-- WHERE o.customer_email = 'aishwarya@example.com'
-- ORDER BY o.created_at DESC;


-- ==============================================================================
-- PRODUCTION SUPABASE AUTOSYNC TRIGGERS, VIEWS, & FUNCTIONS (PURE POSTGRESQL)
-- ==============================================================================

-- 1. Automated Supabase Auth Synchronization Trigger & Function
-- When a real user registers on your website using Supabase Auth (auth.users),
-- this database function runs AUTOMATICALLY inside Supabase to extract and sync 
-- their email, name, phone, address, and city directly into the public.users profile!

CREATE OR REPLACE FUNCTION public.handle_new_user_sync()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (
        id, 
        name, 
        email, 
        password_hash, 
        role, 
        phone, 
        shipping_address, 
        city, 
        postal_code
    )
    VALUES (
        NEW.id::text,
        COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', 'Boutique Customer'),
        NEW.email,
        '', -- Password hash is managed internally by Supabase Auth (auth.users.encrypted_password)
        'customer',
        NEW.phone,
        COALESCE(NEW.raw_user_meta_data->>'shipping_address', NEW.raw_user_meta_data->>'address', ''),
        COALESCE(NEW.raw_user_meta_data->>'city', ''),
        COALESCE(NEW.raw_user_meta_data->>'postal_code', NEW.raw_user_meta_data->>'pincode', '')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute the function AFTER a new signup record is added in auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_sync();


-- 2. Stored Procedure to Manually Register a Real User via Raw SQL
-- If you ever need to register a user directly in the Supabase SQL editor:
-- CALL public.register_new_customer('usr-1002', 'Aishwarya Rai', 'aishwarya@example.com', 'bcrypt_hash', '+919988776655', 'Juhu Scheme', 'Mumbai', '400049');

CREATE OR REPLACE PROCEDURE public.register_new_customer(
    p_id TEXT,
    p_name TEXT,
    p_email TEXT,
    p_password_hash TEXT,
    p_phone TEXT,
    p_shipping_address TEXT,
    p_city TEXT,
    p_postal_code TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.users (
        id, 
        name, 
        email, 
        password_hash, 
        role, 
        phone, 
        shipping_address, 
        city, 
        postal_code
    )
    VALUES (
        p_id, 
        p_name, 
        p_email, 
        p_password_hash, 
        'customer', 
        p_phone, 
        p_shipping_address, 
        p_city, 
        p_postal_code
    );
END;
$$;


-- 3. High-Performance Database View to Track Customer Purchases
-- Unpacks the JSONB items list dynamically. Allows you to retrieve exactly which 
-- products a real customer has purchased with a simple, standard SQL SELECT!
-- Query example:
-- SELECT * FROM public.customer_purchase_history WHERE customer_email = 'aishwarya@example.com';

CREATE OR REPLACE VIEW public.customer_purchase_history AS
SELECT 
    o.id AS order_id,
    o.created_at AS purchase_date,
    o.customer_name,
    o.customer_email,
    o.customer_phone,
    o.status AS order_status,
    o.payment_status,
    item->>'productId' AS product_id,
    item->>'title' AS product_title,
    (item->>'price')::numeric AS unit_price,
    (item->>'qty')::int AS quantity,
    item->>'size' AS selected_size,
    item->>'slug' AS product_slug
FROM public.orders o,
LATERAL jsonb_array_elements(o.items) AS item;
